// The narration is synthesized locally with the macOS Tingting voice.
export const story = [
  { id: 'intro', mode: 'title', section: '读过，然后呢？', title: '标题忘了，\n概念还在。', kicker: '从阅读时的印象，到下一次找回', minimum: 7.5,
    voice: '读过一篇论文，过段时间，标题可能忘了。留在脑海里的，往往只是几个关键词，和一个印象深刻的概念。',
    caption: '标题可能忘了，脑海中的概念还在。' },
  { id: 'idea', mode: 'title', section: 'Paper_Mind 的出发点', title: '通过脑海中的标签，\n找到你的论文。', kicker: '一个轻量、简洁的论文管理平台', minimum: 7.5,
    voice: '让论文库，也按照这些概念来组织。从脑海中的概念，找到已有标签，再找回读过的论文。',
    caption: '脑海中的概念 → 已有标签 → 读过的论文' },
  { id: 'capture', mode: 'popup', section: '01 / 收藏一篇论文', title: '阅读当下，\n顺手收藏。', kicker: '页面信息自动带入，缺失内容可以补充', minimum: 7.0,
    voice: '先从收藏一篇论文开始。打开扩展，检查自动带入的标题、摘要和来源，也可以随时补充和修改。',
    caption: '打开收藏窗口，检查标题、摘要与来源。' },
  { id: 'memory', mode: 'popup', section: '02 / 留下一句记忆', title: '一句话，\n记住它。', kicker: '写下你自己的理解，让下一次回看更容易', minimum: 8.0,
    voice: '再写下一句话，记住它。比如，先验证工具返回的证据，再让智能体回答论文问题。这是你对它的个人印象。',
    caption: '先验证工具返回的证据，再让智能体回答论文问题。' },
  { id: 'tags', mode: 'popup', section: '03 / 选择已有标签', title: '同一个概念，\n沿用同一个标签。', kicker: '名称、别名、说明，都可以帮助你定位标签', minimum: 9.0,
    voice: '输入英文别名，也能找到对应的智能体标签。先读说明，再选择已有分类。需要多少标签就添加多少，数量不设上限。',
    caption: '搜索别名 agent → 选择「智能体」，按需要添加标签。' },
  { id: 'save', mode: 'popup', section: '04 / 保存到本地', title: '印象和笔记，\n一起留下。', kicker: '保存后即可在论文库中查看', minimum: 5.5,
    voice: '选好标签和阅读状态，点击保存。论文、记忆句和阅读笔记，一起进入本地论文库。',
    caption: '保存成功：论文、标签、记忆句与笔记一起保留。' },
  { id: 'library', mode: 'manager', section: '05 / 回到论文库', title: '每一次阅读，都有迹可循。', minimum: 6.0,
    voice: '打开管理页，刚刚收藏的论文已经在这里。卡片上的标签和记忆句，帮助你快速认出它。',
    caption: '刚收藏的论文，已经进入你的阅读积累。' },
  { id: 'recall', mode: 'manager', section: '06 / 从脑海中的概念出发', title: '不记得标题？从一个概念开始。', minimum: 8.0,
    voice: '过几天，只记得它与智能体有关。在顶部输入这个概念，系统先匹配已有标签。描述模糊时，也可以让大模型帮助理解。',
    caption: '先匹配标签名称、别名和说明；也支持 AI 理解模糊概念。' },
  { id: 'find', mode: 'manager', section: '07 / 标签带你找到论文', title: '点选「智能体」，相关论文出现。', minimum: 6.5,
    voice: '点击智能体标签，论文库缩小到相关的三篇。刚才保存的那篇，就在其中。搜索过程不会自动创建新标签。',
    caption: '9 篇收藏 → 3 篇相关论文；搜索不会新建标签。' },
  { id: 'detail', mode: 'manager', section: '08 / 回到当时的理解', title: '找回论文，也找回阅读时的印象。', minimum: 6.0,
    voice: '打开论文详情，当时留下的一句话和阅读笔记都在。找到论文之后，也能接着上次的思考继续读。',
    caption: '回看记忆句、摘要和笔记，接着上一次的思考。' },
  { id: 'status', mode: 'manager', section: '09 / 独立管理阅读进度', title: '概念归标签，进度单独管理。', minimum: 8.0,
    voice: '把这篇论文标记为待重读，再按阅读状态筛选。未读、在读、已读和待重读单独管理，不必再为进度建立标签。',
    caption: '未读 / 在读 / 已读 / 待重读，独立筛选。' },
  { id: 'descriptions', mode: 'manager', section: '10 / 让标签的含义清晰', title: '标签有说明，分类有依据。', minimum: 8.5,
    voice: '你来给标签，大模型结合关联论文的内容，补充含义与适用范围。别名和相似标签合并，帮助分类保持清晰。',
    caption: '人工标签 + 关联论文内容 → 含义与适用范围。', note: '标签说明为预置演示文本，本段未调用模型。' },
  { id: 'models', mode: 'manager', section: '11 / 选择你的模型后端', title: '连接本机 Claude Code 或 Codex。', minimum: 9.5,
    voice: '也可以通过本机桥接，复用已经登录的 Claude Code 或 Codex。分别选择模型和思考强度，让这些设置用于论文分析。',
    caption: 'Claude Code / Codex：独立选择模型和 effort。', note: '设置为操作示例，未连接账号或发起在线生成。' },
  { id: 'api', mode: 'manager', section: '12 / 保留调用方式的选择', title: '也支持兼容 API。', minimum: 7.0,
    voice: '如果使用其他服务，选择兼容 API，填写接口地址和模型名。基础收藏和本地检索，无需配置大模型也能使用。',
    caption: '支持 Chat Completions 兼容 API；基础收藏与查找无需模型。', note: '本机 CLI 仍会连接模型服务，并不代表离线推理。' },
  { id: 'outro', mode: 'outro', section: 'Paper_Mind', title: '让下一次想起，\n成为一次找回。', kicker: '用你记住的概念，找回读过的论文。', minimum: 7.5,
    voice: '让下一次想起，成为一次找回。用你记住的概念，找回读过的论文。现在，就从收藏第一篇论文开始。',
    caption: 'GitHub · ZJU-OmniAI / Paper_Mind' }
];
